# Generated by Django 5.2.7 on 2025-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0002_ingredient_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='menuapi.ingredient')),
            ],
        ),
    ]
